### PR TITLE
List a tiny JS world by Zophrox

### PR DESCRIPTION
**Pull request by zophrox**

### CODE REVIEW

**Comment by OleksiyRudenko** [comment]
It is important to have an empty line at the end of file. So when someone makes a contribution your addition won't be affected and marked as changed.
Github gui may require two empty lines to ensure there is at least one.
Please, fix.

If a merger conflict arises, please, resolve.

**Comment by zophrox** [comment]
A minute

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Вірусів
немає. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

ср, 26 груд. 2018 о 19:42 Oleksiy Rudenko <notifications@github.com> пише:

**Comment by zophrox** [comment]
ready


ср, 26 груд. 2018 о 19:44 Oleg Kuntyy <zophrox@gmail.com> пише:

**Comment by OleksiyRudenko** [comment]
@zophrox Please, resolve the conflict as an earlier PR has introduced some updates.

**Comment by zophrox** [comment]
sorry, maybe I do not do something like that, but I have not yet fully understood

**Pull request merged**
