### PR TITLE
add new inhabitants

### PR DESCRIPTION
**Pull request by sioniks**

### CODE REVIEW

**Comment by OleksiyRudenko** [comment]
@sioniks 
Thank you for your submission.

However, this repo doesn't accept PRs to core code.
Please, do the following:

**Publishing demo web-site**
1. In your local clone merge `populate-world` (or a branch you developed the code at) into `gh-pages` and push to your own origin
2. In your [fork](https://github.com/sioniks/a-tiny-JS-world) [Settings](https://github.com/Mynziak/a-tiny-JS-world/settings) make sure that repo is published on GitHub pages and take a note of your demo URL.
3. In your [fork](https://github.com/sioniks/a-tiny-JS-world) main page find **Edit** button and change web site address with your own demo page link from item 2 above.

**Submitting code for review**
1. Follow instructions as per [kottans/frontend-2019-homeworks repo](https://github.com/kottans/frontend-2019-homeworks)
2. Publish (copy-paste) only script files. That is sufficient to conduct a code review.
3. You will also need a link to your demo

You may want to take a look at how other similar [open](https://github.com/kottans/frontend-2019-homeworks/pulls) and [closed](https://github.com/kottans/frontend-2019-homeworks/pulls?q=is%3Apr+is%3Aclosed) PRs were submitted.

P.S. We know copy/pasting is not really a git way of doing things but we do not want to confuse students with not easy to catch up git `subtree`, `submodule`, `subrepo` workflows.

Please, let me know if you need any help to complete the above.

I will close this PR once you have the above accomplished.

**Comment by sioniks** [comment]
i fix all my trouble. Please review

**Comment by OleksiyRudenko** [comment]
Please, explain your understanding of the following from the comment above in this thread, or ask a question.
> However, this repo doesn't accept PRs to core code.

**Comment by sioniks** [comment]
@OleksiyRudenko I do not understand why the branch master merge into my other branch. This happens automatically when I do git push. Can you help me?

**Comment by sioniks** [comment]
I moved the code to the desired repository. This is my mistake, sorry. This PR is no longer relevant.

**Pull request closed without merging**
