### PR TITLE
List a tiny JS world by Evgeniy241984

### PR DESCRIPTION
**Pull request by Evgeniy241984**

### CODE REVIEW

**Comment by OleksiyRudenko** [comment]
@Evgeniy241984 thank you for your submission.
Please resolve the conflict

**Comment by OleksiyRudenko** [comment]
@Evgeniy241984 do you need any support on conflict resolution?

**Comment by Evgeniy241984** [comment]
Yes. 
As far as I understand, Do I need  to change the position of the record?

**Comment by OleksiyRudenko** [comment]
@Evgeniy241984 you need to update your fork with current state of this repo master, resolving the conflict.
You can add your line at a position at your discretion. Somewhere between exiting rows is OK. Would be good if date in your row in final table was more or less consistent with other dates.

**Comment by Evgeniy241984** [comment]
Done. Conflict resolved! Thank you!

**Review by OleksiyRudenko — APPROVED** [review]
👍

**Pull request merged**
